# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/a55x-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a55x,$(TARGET_DEVICE)),)

endif
